print("Welcome to the Band Name Generator.")
name = input("What is your name? \n")
print("Hello" + " " + name + "!")
city = input("What is the name of the city you grew up in? \n")
pet = input("What is the name of your pet? \n")
print("Your band name could be " + city + " " + pet)