name = input("What is your name? \n")
age = input("What is your age? \n")
college = input("What is your college name? \n")
branch = input("Which is your branch? \n")
job = input("What is your dream job? \n")
print("========== STUDENT CARD ==========")
print("Name: " + name)
print("Age: " + age)
print("College: " + college)
print("Branch: " + branch)
print("Dream Job: " + job)
print("==================================")